version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: library123
    ports:
      - "5432:5432"

  web:
    build: .
    command: npm start
    volumes:
      - ./src:/app/src
    ports:
      - "3000:3000"
    depends_on:
      - postgres
