version: '3'
services:
  postgres:
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"

  web:
    build: .
    command: npm start
    volumes:
      - ./src:/app/src
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    env_file:
      - .env
